jina-ai/finetuner

.github/requirements-cicd-gpu.txt, .github/requirements-cicd.txt, finetuner/tuner/pytorch/miner.py, tests/conftest.py, tests/unit/tuner/torch/test_miner.py
This PR extends the current `Miner` with `Session Miners`, generate all possible tuples/triplets w.r.t each session (anchor).
=> feat(tuner): add miner for session dataset

finetuner/tailor/paddle/__init__.py, finetuner/tailor/pytorch/__init__.py
bug for `to_embedding_layer` (fixed for torch and paddle, tf works fine):
Reason: after attach a new layer to the end of model (user specify a different `output_dim`), `Paddle` and `Pytorch` added `_LinearAtLast` module, and `linear` layer will be considered as a part of `_LinearAtLast`, `is_embedding_layer` became `False`.
before: 
after:
=> fix(tailor): fix to emebdding model

finetuner/helper.py, tests/unit/test_get_framework.py
Right now, `get_framework` is not robust, it fails against any kind of third party modules (ones created by user or from libraries like `transformers`). See this test below (fails with current `main`):
```python
def test_torch_custom():
class MyModel(torch.nn.Module):
pass
model = MyModel()
assert 'torch' == get_framework(model)
```
This PR fixes that by using `isinstance` for checking. However, this requires importing the corresponding framework (e.g. `torch`) - which can be a problem, as it would require all 3 frameworks to be installed just for inference. To circumvent this, a check is performed whether the framework is installed at all.
This is not ideal still - namely, if the user has all 3 frameworks installed (very rare case, but still), it can be the case that all 3 are imported …
=> fix: make get_framework robust

docs/_static/docbot.css, docs/_static/docbot.js
This fixes a bug in the previous patch that the doc-bot grows infinitely upon multiple questions and won't trigger a scroller.
Fixes the automatic scroll-to-bottom position.
Fixes multiple concurrent query when `enter` is pressed multiple times.
=> fix: docbot overflow and scrolling

docs/_static/docbot.css, docs/_templates/docbot.html
This fixes the feedback tooltip broken issue when the answer is too short.
Although finetuner docbot rarely return short answers to get a buggy screenshot,
It's better to keep code the same with Jina doc.
From:
To:
=> fix(docbot): feedback tooltip ui style

finetuner/tailor/keras/__init__.py, finetuner/tailor/paddle/__init__.py, finetuner/tailor/pytorch/__init__.py, tests/unit/tailor/test_keras.py, tests/unit/tailor/test_paddle.py, tests/unit/tailor/test_torch.py
in this PR, we added a `freeze_layers` parameter as argument of `to_embedding_layer`, which takes a list of `str`, allow user to freeze model by specific layer names. If user didn't specify `freeze_layers` and `freeze` is `True`, we freeze all layers. 
we also lifted restriction on output dimensionality, to allow any layer of `embedding_layers` serve as feature extractor.
Next step:
1. flatten embedding layer if last layer is > 2d.
2. always attach a new output layer as defined by `output_dim`.
=> feat(tailor): support freeze by layer names

.github/requirements-cicd-gpu.txt, .github/requirements-cicd.txt, .gitignore, finetuner/__init__.py, finetuner/tuner/__init__.py, finetuner/tuner/base.py, finetuner/tuner/callback/__init__.py, finetuner/tuner/callback/progress_bar.py, finetuner/tuner/callback/wandb_logger.py, tests/unit/tuner/callback/test_wandb.py
This adds support for logging with WandB - when we add learning rate scheduling (and proper evaluation) this will be expanded.
Here's how to use it
```python
from finetuner.tuner.callback import WandBLogger
finetuner.fit(
embed_model,
callbacks=[WandBLogger()],
train_data=generate_fashion(num_total=2000),
eval_data=generate_fashion(is_testset=True, num_total=1000),
)
```
Here's how the logs then look like in wandb
=> feat: add wandb logger

tests/conftest.py, tests/integration/torch/test_overfit.py
Without setting manual seed, in each test runs
- Batch sampler gives different batches
- Model fine-tuned reports different embedding because the weights initialise are always random
This causes the embeddings to be different each time and thus test is flaky
Closes issue #252
=> fix(test): fix flaky overfit test

finetuner/__init__.py, finetuner/tuner/__init__.py, finetuner/tuner/base.py, finetuner/tuner/dataset/base.py, finetuner/tuner/dataset/samplers.py, finetuner/tuner/keras/__init__.py, finetuner/tuner/paddle/__init__.py, finetuner/tuner/pytorch/__init__.py, tests/integration/conftest.py, tests/integration/keras/test_num_workers.py, tests/integration/paddle/test_num_workers.py, tests/integration/torch/test_num_workers.py
=> feat: add multiprocessing dataloading

finetuner/tuner/evaluation.py, setup.py
The jina.math module has been moved to `docarray`. 
This PR changes the imports accordingly, to fix the failing tests.
=> fix: evaluation imports imports to reflect new code structure

finetuner/tuner/base.py, finetuner/tuner/callback/base.py, finetuner/tuner/callback/progress_bar.py, finetuner/tuner/keras/__init__.py, finetuner/tuner/paddle/__init__.py, finetuner/tuner/pytorch/__init__.py, tests/integration/conftest.py, tests/integration/keras/test_callback.py, tests/integration/paddle/test_callback.py, tests/integration/torch/test_callback.py
This adds a new `on_exception` hook to the callbacks. It is used in progress bar to properly shut it down if an exception occurs.
=> fix: handle exceptions in callbacks

finetuner/tailor/keras/projection_head.py, finetuner/tailor/paddle/projection_head.py, finetuner/tailor/pytorch/projection_head.py, finetuner/tuner/augmentation.py, tests/unit/tuner/test_augmentation.py
a set of minor updates based on experiments:
1. change `num_layers` of `projection_head` to 2. based on simclrv2 paper.
2. added another `batchnorm1d` at the end of default `projection_head`.
3. add `phrase` option in `vision_preprocessor`, to apply augmentation at evaluation time.
=> fix: add normalization to preprocessor

finetuner/embedding.py
batch size 64 ~ paddle, also fixed `collate_fn` in paddle, we're doing it two times.
```
124 1001.613 MiB           1           b.embeddings = embed_model(batch_inputs).numpy()
124  501.785 MiB           1           b.embeddings = embed_model(batch_inputs).numpy()
124 1501.672 MiB           1           b.embeddings = embed_model(batch_inputs).numpy()
124  7364.125 MiB           1           b.embeddings = embed_model(batch_inputs).numpy()
124  10206.613 MiB           1           b.embeddings = embed_model(batch_inputs).numpy()
```
=> fix: use small batch size by default

finetuner/device.py, finetuner/embedding.py, finetuner/excepts.py, finetuner/tailor/__init__.py, finetuner/tailor/base.py, finetuner/tailor/keras/__init__.py, finetuner/tailor/paddle/__init__.py, finetuner/tailor/pytorch/__init__.py, finetuner/tuner/keras/__init__.py, finetuner/tuner/paddle/__init__.py, finetuner/tuner/pytorch/__init__.py, tests/unit/tailor/keras/test_keras.py, tests/unit/tailor/paddle/test_paddle.py, tests/unit/tailor/pytorch/test_pytorch.py
This is a draft to address issue #368. There is still an issue which occurs if specific paddle models (e.g. LSTM models) are assigned to a device with the paddle.fluid.dygraph.layers.to function.
=> Refactor device module 368

setup.py
downgrade docarray due to error in `match` function.
=> fix: fix the docarray version to pass unit tests

CHANGELOG.md, finetuner/__init__.py, finetuner/client/base.py, finetuner/client/client.py, requirements.txt, tests/integration/conftest.py, tests/unit/mocks.py, tests/unit/test_client.py
Closes https://github.com/jina-ai/finetuner/issues/445
Removes `path` and `dotenv` from the requirements.
=> refactor: remove path and dotenv

CHANGELOG.md, finetuner/constants.py, tests/conftest.py
after the API prod deployment, before beta testing, we need to change the default API and Hubble registry to prod. While testing, use staging for integration test.
link to the internal issue: https://github.com/jina-ai/finetuner-api/issues/87
=> refactor: use prod environment by default

CHANGELOG.md, docs/2_step_by_step/2_1_install.md, finetuner/__init__.py
this patch release has changed the default host from staging to prod, readme polishment and dependency clean up.
=> chore: 0.2.2 release

CHANGELOG.md, docs/3_finetuner_in_action/3_3_text_to_image.md
Part of https://github.com/jina-ai/finetuner/issues/451
Closes https://github.com/jina-ai/finetuner/issues/453
Refactor text to image fine-tuning example based on the new template
=> docs: refactor text to image example

CHANGELOG.md, finetuner/__init__.py
change default `learning_rate` to `None` since optimizers such as `SGD`, `Adam` needs `learning_rate` while some not.
Some docstring format change.
=> refactor: reset default params and docstring format

CHANGELOG.md, README.md
This PR removes `time` column in the readme table, which makes table shows correct and this column is useless since it has a linear relationship against training data size and device.
=> chore: remove time column from table

CHANGELOG.md, README.md
Update readme, use `finetuner.jina.ai` as documentation links to replace netlify preview links. It will be visitable after we merge dev into the main branch.
=> fix: readme links

CHANGELOG.md, docs/walkthrough/create-training-data.md, docs/walkthrough/integrate-with-jina.md
This PR fixes `prepare training data` section, when user give an image uri, this image uri should use `uri` property rather than content.
---
=> docs: replace content to uri if use image

CHANGELOG.md, finetuner/__init__.py, finetuner/client/base.py, finetuner/client/client.py, finetuner/constants.py, finetuner/exception.py, finetuner/finetuner.py, finetuner/hubble.py, finetuner/run.py, tests/integration/test_runs.py
This PR allows user to get user token from Hubble, and get artifact id once fine-tuning is done. Usage:
```python
finetuner.login()
token = finetuner.get_token()
run = finetuner.get_run(run_name='something')
artifact_id = run.artifact_id
```
This allows user to directly pull artifact inside `FinetunerExecutor` using`token` and `artifact` as `artifact_id`.
This PR also did some minor refactoring on `download_artifact` and error handling.
A follow up PR will be created to update documentation including the usage of `FinetunerExecutor`.
---
=> feat: add artifact id and token endpoint

CHANGELOG.md, docs/walkthrough/run-job.md
Removes out-dated CLIP specific documentation to align with the new `fit` function.
---
=> docs: remove out-dated clip specific documentation

CHANGELOG.md, requirements.txt
To resolve the conflict between `jina-hubble-sdk` and jina in async functions: https://github.com/jina-ai/hubble-client-python/pull/49
---
=> chore: bump hubble python sdk to 81

CHANGELOG.md, finetuner/exception.py, finetuner/finetuner.py
Create client automatically if user is already logged in
---
If the user is already logged in, finetuner can be used without calling `finetuner.login()`. This is especially helpful for people who want to integrate finetuner with other jina libraries that use hubble. Moreover, I add some useful exceptions if the user is not logged in and tries to call some functions which require a login.
=> fix: create client automatically if user is logged in

CHANGELOG.md, docs/walkthrough/choose-backbone.md, finetuner/__init__.py, finetuner/model.py, setup.py
Starting from `0.9.4`, we'll support much more models as backbones for fine-tune. in this PR we add new stubs and documentation.
documentation change: https://ft-refactor-stubs--jina-docs.netlify.app/refactor-stubs/walkthrough/choose-backbone/#backbone-model
---
=> refactor: adopt changes in open clip models

CHANGELOG.md, README.md, finetuner/__init__.py
Minor changes to readme and __init__
---
This adds the readme changes from https://github.com/jina-ai/finetuner/pull/530 and make `connect` available directly from the finetuner module
=> refactor: update readme and add connect function

CHANGELOG.md, docs/walkthrough/integrate-with-jina.md
should use latest finetuner executor version in docs.
---
=> docs: fix finetuner executor version

CHANGELOG.md, README.md, docs/tasks/text-to-image.md
The evaluation metric scores for finetuning clip where not correct. Now, I used a bigger portion of the fashion captioning dataset for finetuning, slightly changed the hyperparmeter to values which work better and update the evaluation metric scores
---
=> docs: update metric tables and hyperparameters for clip finetuning

CHANGELOG.md, docs/tasks/text-to-image.md, docs/walkthrough/using-callbacks.md
In this PR, we start to support WiSE-FT fine-tuning for models with a strong zero-shot capability, to merge weights between pre-trained model and zero-shot model. Currently all CLIP-family models are supported. Functionality has been implemented inside core. To make use of it:
```diff
run = finetuner.fit(
model='ViT-B-32#openai',
...,
loss = 'CLIPLoss',
-    callbacks=[],
+    callbacks=[WiSEFTCallback(alpha=0.4)],
)
```
Review documentation change [here](https://ft-docs-wise-ft--jina-docs.netlify.app/docs-wise-ft/tasks/text-to-image/#advanced-wise-ft)
---
=> docs: add wise-ft to clip finetuning

CHANGELOG.md, README.md, docs/_templates/template_ft_in_action.md, docs/get-started/how-it-works.md, docs/tasks/image-to-image.md, docs/tasks/text-to-image.md, docs/tasks/text-to-text.md, docs/walkthrough/index.md, docs/walkthrough/integrate-with-jina.md, docs/walkthrough/login.md, docs/walkthrough/save-model.md, finetuner/__init__.py, finetuner/finetuner.py, setup.py, tests/integration/conftest.py, tests/unit/mocks.py
The latest hubble sdk release brings finetuner sdk user experience improvement, see screenshot as follows:
After success:
---
=> feat: adopt hubble sdk on notebook login

CHANGELOG.md, docs/tasks/image-to-image.md, docs/tasks/text-to-image.md, docs/tasks/text-to-text.md, docs/walkthrough/run-job.md, docs/walkthrough/using-callbacks.md, finetuner/__init__.py, finetuner/experiment.py, finetuner/finetuner.py, setup.py, tests/unit/test_experiment.py
Resolve inconsistency between `fit` end `get_model`, in `fit` we use `cpu`, in `get_model` we use `gpu`. Better to align with Docarray `device='cpu'` or `device='cuda'`.
This will not be a breaking change for internal users. 
This will be a breaking change for ppl install `finetuner-full`  when calling `get_model`.
A follow up ticket has been created to remove `cpu` in `0.7.0` #578 
```diff
run = finetuner.fit(
...,
-   cpu=False,  # cpu is still supported, no breaking change, we sunset `cpu` after 0.7
+   device='cuda', # note, now `cuda` is the default device.
)
inference_engine = finetuner.get_model(
...,
-    gpu=True, 
+    device='cuda',  # note, `cpu` is the default device unless user specify `cuda`.
)
```
---
=> refactor: unify cpu gpu into device

CHANGELOG.md, README.md, docs/_templates/template_ft_in_action.md, docs/tasks/image-to-image.md, docs/tasks/text-to-image.md, docs/tasks/text-to-text.md, docs/walkthrough/index.md, docs/walkthrough/integrate-with-jina.md, docs/walkthrough/login.md, docs/walkthrough/run-job.md, docs/walkthrough/save-model.md, docs/walkthrough/using-callbacks.md
A list of documentation improvements before release:
1. everything related to cloud storage, Hubble, ecosystem renamed to Jina AI Cloud.
2. document `device='cuda'` in `get_model`.
3. Remove gpu application form.
---
=> docs: unify everything to jina ai cloud

CHANGELOG.md, docs/walkthrough/choose-backbone.md
Update names of open clip models
---
We are going to change the the separator in the names of the open clip models from `#` to `::`
=> docs: update names of open clip models

CHANGELOG.md, finetuner/__init__.py, setup.py
Usability improvements `encode`:
1. interpret device type if `device` is not provided.
2. `show_progress` while batching DocumentArray when calling `encode`.
---
=> refactor: show progress while encoding

CHANGELOG.md, docs/_templates/sidebar/navigation.html, docs/walkthrough/integrate-with-jina.md
`hub.jina.ai` has been replaced with `cloud.jina.ai`.
---
=> docs: upgrade to new hub uri to cloud uri

docs/walkthrough/create-training-data.md
Small pr to clarify two things:
- data supplied as a CSV file with two elements per row will not be able to support sampling methods that require more than two elements per class
- uris for local images can be loaded as blobs now
---
=> docs: clarified docs

CHANGELOG.md, docs/walkthrough/using-callbacks.md
We'll support `WandBLogger` in 0.6.5, with [Anonymous Mode](https://docs.wandb.ai/ref/app/features/anon), no need to send WandB `api_key` to us.
---
=> docs: add wandb callback docs

CHANGELOG.md, docs/walkthrough/choose-backbone.md, docs/walkthrough/run-job.md, finetuner/__init__.py, finetuner/console.py
The current `describe_model` is a bit mess given so many backbones are supported. I added a parameter `task` to allow user filter backbone by task, Documentation should be more straightforward.
---
=> docs: better describe models on task

README.md
Add comment abou run name in README
---
If users run the example in the README twice, they might wonder about this exception:
```bash
finetuner.excepts.FinetunerServerError: Conflict (409): Run 'resnet50-tll-run' for experiment 'finetuner' already exists
```
Therefore, I would suggest to add a note about run names to be unique.
=> add comment for run name

CHANGELOG.md, docs/notebooks/text_to_image.ipynb
After the release the text-to-image notebook is now running. This PR just updates the notebook to be coherent with the markdown file.
---
=> chore: align text-to-image notebook with markdown

CHANGELOG.md, finetuner/data.py
Currently, attempting to encode data from a list using a CLIP model made using `get_model` will result in an error, this pr prevents that by changing the method of determining the inferring the modality of the model
---
=> Fix build encoding dataset

CHANGELOG.md, docs/notebooks/image_to_image.ipynb, docs/notebooks/image_to_image.md, docs/notebooks/text_to_image.ipynb, docs/notebooks/text_to_image.md
This PR modifies the hints in notebooks to load images to blobs instead of tensors.
---
=> docs: modify hints to use blobs instead of tensor

.github/workflows/remote-ci.yml, CHANGELOG.md
This pr adds a CI job that can be manually triggered and will run tests on finetuner-core
currently, the core-ci workflow can be triggered in two ways:
A workflow dispatch, in which a user can manually trigger the workflow from the actions tab of this repo
A repository dispatch, in which the another repository (expected to be core) can remotely trigger the workflow.
Both of these methods only work when the workflow exists on the master branch, meaning that this pr needs to be tested before it can be merged
---
=> ci: add remote-ci for core

CHANGELOG.md, Makefile, finetuner/__init__.py, finetuner/client/client.py, finetuner/experiment.py, finetuner/finetuner.py, tests/integration/test_experiments.py, tests/unit/mocks.py, tests/unit/test_finetuner.py
Due to our recent API changes (mostly paginated results), the staging env for integration test is not working anymore. In this PR the changes has been adopted, also added an extra parameter `size=50` to allow user set return number.
1. Update all endpoints based on recent API changes.
2. Change default `experiment_name` as `default`.
3. Remove `full-trace` from pytest to make github actions error messages easier to read.
---
=> refactor: adopt api changes

CHANGELOG.md, README.md, docs/notebooks/image_to_image.ipynb, docs/notebooks/image_to_image.md, docs/notebooks/mesh_to_mesh.ipynb, docs/notebooks/mesh_to_mesh.md, docs/notebooks/multilingual_text_to_image.ipynb, docs/notebooks/multilingual_text_to_image.md, docs/notebooks/text_to_image.ipynb, docs/notebooks/text_to_image.md, docs/notebooks/text_to_text.ipynb, docs/notebooks/text_to_text.md, docs/walkthrough/using-callbacks.md
Add namespace to artifact names in the documentation
---
Updates all artifact names in the documentation and the README to include the namespace prefix `finetuner`.
Contains some changes from https://github.com/jina-ai/finetuner/pull/643, because the notbooks already contain them.
=> docs: add namespace to artifact names

CHANGELOG.md, docs/walkthrough/create-training-data.md
Add hints in docs how to escape common when prepare training data using csv.
---
=> docs: escape comma

CHANGELOG.md, docs/walkthrough/choose-backbone.md
For CLIP models with a ResNet vision tower, due to limited (0) usage we'll delete them in the next release. Add back `efficient_b7` to the image-to-image search since now we have a better pretrained weights.
Note, ALL weights from torchvision has been replaced with better `IMAGENETV2`.
---
=> docs: remove rn backbones add effnetb7

CHANGELOG.md, README.md, docs/advanced-topics/linear-probe.md, docs/advanced-topics/negative-mining.md, docs/advanced-topics/using-callbacks.md, docs/get-started/how-it-works.md, docs/notebooks/image_to_image.ipynb, docs/notebooks/image_to_image.md, docs/notebooks/mesh_to_mesh.ipynb, docs/notebooks/mesh_to_mesh.md, docs/notebooks/multilingual_text_to_image.ipynb, docs/notebooks/multilingual_text_to_image.md, docs/notebooks/text_to_image.ipynb, docs/notebooks/text_to_image.md, docs/notebooks/text_to_text.ipynb, docs/notebooks/text_to_text.md, docs/walkthrough/choose-backbone.md, docs/walkthrough/create-training-data.md, docs/walkthrough/index.md, docs/walkthrough/inference.md, docs/walkthrough/login.md, docs/walkthrough/run-job.md, docs/walkthrough/save-model.md
Fix typos and duplicate text in docs
---
I removed the duplicate part in the documentation and fixed a couple of typos and minor wrong formulations.
=> docs: fix typos etc

CHANGELOG.md, README.md, docs/index.md
Add section about articles about finetuner
---
just add a section to the Readme and the docs which reference the blog posts about finetuner. If you have more to reference, let me know.
=> docs: add section about articles about finetuner

docs/advanced-topics/advanced-losses-optimizers-and-poolers.md
This pr corrects a mistake in the code example for setting pooler options
---
=> docs: correct code example for pooler options

CHANGELOG.md, finetuner/client/client.py, setup.py, tests/conftest.py, tests/unit/test_client.py
chore: bump hubble version
---
=> chore: bump hubble version

CHANGELOG.md, finetuner/constants.py, setup.cfg, setup.py
This PR release Finetuner to 0.7.1
---
=> chore: release 0.7.1

CHANGELOG.md, docs/advanced-topics/advanced-losses-and-optimizers.md, docs/index.md, docs/notebooks/image_to_image.ipynb, docs/notebooks/image_to_image.md, docs/notebooks/image_to_image_arcface.ipynb, docs/notebooks/image_to_image_arcface.md
This pr adds a new notebook to the documentation that uses `ArcFaceLoss` function.
---
=> docs: add notebook to demonstrate use of ArcFaceLoss

CHANGELOG.md, docs/advanced-topics/advanced-losses-optimizers-and-poolers.md, docs/index.md
This pr adds the section on GeM pooling that was previously removed
---
=> docs: Add documentation for GeM pooling

.github/workflows/ci.yml, CHANGELOG.md, setup.py
This pr adds support for python 3.10, as well as adding a test to the ci that attempts to install finetuner for all supported versions. Currently, we cannot support python 3.11 as it is not supported by ONNX runtime
---
=> chore: support python3.10

CHANGELOG.md, finetuner/finetuner.py
This pr checks if `experiment` has successfully been set before starting a run, and will raise a ValueError if not.
---
=> feat: add error message when experiment is `None`

CHANGELOG.md, finetuner/client/base.py, finetuner/client/client.py
This pr attempts to prevent tests in `integration/test_runs.py` from failing at random. The current causes for failure are outlined in the linked issue.
---
=> fix: reduce flakiness of tests

.github/workflows/ci.yml, CHANGELOG.md, setup.cfg, setup.py
=> fix: downgrade docarray

.pre-commit-config.yaml, CHANGELOG.md, finetuner/data.py, setup.py, tests/integration/test_data.py, tests/integration/test_experiments.py, tests/integration/test_runs.py, tests/unit/test___init__.py, tests/unit/test_data.py
---
Bump black to version 23.3.0, flake8 to 6.0.0 and isort to 5.12.0.
=> chore: bump black, flake8, isort

CHANGELOG.md, finetuner/experiment.py
Create synthesis run currently only accepts a `str` is the name of the `DoccumentArray`, or a list of `str` which is to used to construct a `DocumentArray`, but if user give a DA, it is not accepted.
---
=> fix: create synthesis run should accept da as input

CHANGELOG.md, README.md, docs/walkthrough/choose-backbone.md, finetuner/__init__.py, setup.cfg, setup.py
=> feat: add jina embedding models

CHANGELOG.md
Draft release note:
This release covers Finetuner version 0.7.9, including dependencies finetuner-core 0.13.9.
This release contains 1 new features and 1 refactoring.
We have made contributions to the open source community by releasing three pre-trained embedding models:
1. `jima-embedding-s-en-v1`: 35 million parameter compat embedding model.
2. `jina-embedding-b-en-v1`: 110 million parameter standard sized embedding model.
3. `jina-embedding-l-en-v1`: 330 million parameter large embeddding model.
All three embedding models have been trained using Jina AI's Linnaeus-Clean dataset. This dataset consists of 380 million pairs of sentences, which include both query-document pairs. These pairs were obtained from various domains and were carefully selected through a thorough cleaning process. …
=> chore: release 079

CHANGELOG.md, docs/get-started/installation.md, docs/get-started/pretrained.md, docs/index.md
Add docs for embedding model page.
---
=> docs: add embedding page

CHANGELOG.md, docs/walkthrough/choose-backbone.md, setup.cfg, setup.py
This release covers Finetuner version 0.8.1, including dependency finetuner-core 0.13.10.
This release contains 1 new feature, 1 refactoring and 1 documentation improvement.
We have included `jina-embedding-t-en-v1` in our list of supported models. This very small embedding model, comprising 14 million parameters, offers lightning-fast inference on CPUs.
In our experiments, it was able to encode 1730 sentences per second on a Macbook Pro Core-i5, making it perfectly suitable for edge devices. To utilize the Tiny model, follow these steps:
```python
!pip install finetuner
model = finetuner.build_model('jinaai/jina-embedding-t-en-v1')
embeddings = finetuner.encode(
model=model,
data=['how is the weather today', 'What is the current weather like today?']
) …
```
=> chore: release 081
