- .github/requirements-cicd-gpu.txt
- .github/requirements-cicd.txt
- tests/integration/fit/test_fit_lstm.py
- tests/integration/fit/test_fit_mlp.py
- tests/unit/tuner/dataset/test_class_sampler.py
~once after framework version settled will try to increase tf version.~
Note: I also decreased `num_total` in CI integration test `fit` to make it a bit faster.
> ci: pin framework version

- finetuner/embedding.py
some BN, Dropout tests need to be added
> fix(embedding): fix embedding train/eval time behavior

- docs/_static/docbot.css
- docs/_static/docbot.js
- docs/_templates/docbot.html
Fix doc-bot style broken before load.
Fix potential issue that may cause doc-bot fail to load.
> docs: fix doc-bot style during load

- docs/basics/datasets/class-dataset.md
- docs/basics/datasets/session-dataset.md
- docs/get-started/swiss-roll/index.md
> docs: fix typos 1

- finetuner/__init__.py
`freeze_layers` has been implemented in `tailor` classes, this PR add the missing arguments to `fit` function.
> feat(tailor): add freeze layers to fit

- finetuner/tuner/callback/best_model_checkpoint.py
> fix: make sure logging is correct

- docs/get-started/covid-qa.md
- finetuner/labeler/ui/js/components/sidebar.vue.js
- finetuner/tuner/callback/best_model_checkpoint.py
> chore: fix typos in covid-qa

- docs/basics/data-format.md
- docs/basics/datasets/instance-dataset.md
- finetuner/tuner/dataset/__init__.py
- finetuner/tuner/dataset/base.py
- finetuner/tuner/dataset/datasets.py
- finetuner/tuner/dataset/samplers.py
- tests/unit/tuner/dataset/test_instance_dataset.py
- tests/unit/tuner/dataset/test_instance_sampler.py
> feat: add unlabeled data classes

- docs/get-started/totally-looks-like/index.md
new `docarray` do not have `sort` anymore.
> docs: replace sort with sorted

- finetuner/tuner/pytorch/__init__.py
> Use module level collate all function in PyTorch tuner

- README.md
- docs/get-started/3d-mesh/index.md
a quick fix on readme and docs.
> docs: clean up readme and ndcg

- finetuner/tuner/dataset/samplers.py
> fix: shuffle batches

- docs/get-started/totally-looks-like/index.md
> docs: typos

- docs/get-started/3d-mesh/index.md
Adapt to the changes of  https://github.com/jina-ai/executor-3d-encoder/pull/7
> docs: fix models import

- finetuner/tuner/callback/progress_bar.py
fix progress bar not updated in jupyter.
> fix: progress bar in notebook

- docs/_templates/page.html
- docs/conf.py
> docs: update qa-bot to v0.4

- docs/_templates/page.html
- docs/conf.py
Fixed below issues for qabot:
1. flashing when scrolling on ios
2. disappearing on search and 404 page
And removed obsolete theme configuration for qabot.
> docs(qabot): fix flash on ios and disappear on search&404 page

- CHANGELOG.md
- finetuner/client/base.py
- finetuner/client/exception.py
- finetuner/run.py
Implements basic error handling.
We can come up with more sophisticated error classes/types after.
> feat: implement basic error handling

- CHANGELOG.md
- finetuner/hubble.py
- tests/integration/conftest.py
- tests/integration/test_runs.py
Closes https://github.com/jina-ai/finetuner.fit/issues/232
> fix: `download_artifact` throws error

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/finetuner.py
- tests/integration/test_experiments.py
- tests/integration/test_runs.py
To support this functionality:
```python
finetuner.create_experiment()
finetuner.get_experiment(name)
finetuner.list_experiments()
finetuner.delete_experiment(name)
finetuner.delete_experiments()
```
> feat: add experiment-related methods to finetuner

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/constants.py
> feat: add default values for finetuner host and hubble registry

- CHANGELOG.md
- docs/2_step_by_step/2_2_experiment_and_run.md
- docs/2_step_by_step/2_3_login_to_jina_ecosystem.md
- docs/2_step_by_step/2_4_create_training_data.md
see it lively here: https://ft-docs-step-by-step--jina-docs.netlify.app/docs-step-by-step/2_step_by_step/2_1_install/
please review step-by-step section:
1. installation
2. Two basic concepts: Experiment and Run
3. Login to Jina ecosystem
4. Create training and evaluation (Optional) data
I'll create a follow-up PR for the rest of the step-by-step pages.
> docs: step by step - part 1

- CHANGELOG.md
- finetuner/__init__.py
- requirements.txt
A bit explanation on the support backbone model, attached 2 new models in the runner from @violenil 's transformer PR.
it is needed when writing documentation on the step-by-step guide.
> refactor: explain list models

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/finetuner.py
> feat: expose run methods

- .github/workflows/ci.yml
- setup.py
Tests are failing with old docarray
> chore: set `protobuf` version to `3.20.1`

- docs/_templates/template_ft_in_action.md
This is a template for the guides in our documentation.
> docs: add guide template

- CHANGELOG.md
- finetuner/__init__.py
> chore: release 0.2.0

- CHANGELOG.md
- docs/2_step_by_step/2_1_install.md
- finetuner/__init__.py
release small documentation and request fix to roll out beta testing
> chore: release 0.2.1

- CHANGELOG.md
- docs/3_finetuner_in_action/3_2_image_to_image.md
Part of https://github.com/jina-ai/finetuner/issues/451
Closes https://github.com/jina-ai/finetuner/issues/453
Refactor image to image fine-tuning example based on the new template
> docs: refactor image to image example

- README.md
- docs/tasks/text-to-image.md
This PR updates the evaluation results of the CLIP example in the README and the documentation.
> docs: update clip example in readme and docs

- .github/workflows/cd.yml
- .github/workflows/force-docs-build.yml
- .releaserc.json
- CHANGELOG.md
- docs/conf.py
- docs/tasks/text-to-image.md
- docs/walkthrough/install.md
- finetuner/__init__.py
- setup.cfg
- setup.py
add back CD to push documentation and release to pypi, integrated with semantic release.
> ci: add back cd

- .github/workflows/cd.yml
> ci: add pypi username to cd

- .github/workflows/ci.yml
- CHANGELOG.md
- docs/walkthrough/install.md
fix the rendering of documentation install finetuner page: 
Also added `success-all-tests` back to make it un-blocking.
---
> docs: fix installation format

- docs/_templates/page.html
- docs/conf.py
This PR adds qa bot to documentation website.
> feat(docs): add qabot to docs website

- CHANGELOG.md
- finetuner/hubble.py
- requirements.txt
usability improvement, when calling `save_model`, the client just hangs without any progress given the model is too large.
---
> refactor: show progress when save model

- CHANGELOG.md
- setup.cfg
Bring finetuner-sdk to 0.5.1 which brings bug fixes, usability improvements and documentation improvements.
---
> chore: release 0.5.1

- CHANGELOG.md
- finetuner/callback.py
> feat: add wandb callback arguments

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/client/client.py
- requirements.txt
Minor code improvements, include bump hubble, and potential bug fix given log entry is empty.
---
> refactor: mark fit login required

- CHANGELOG.md
- setup.cfg
bump finetuner client to 0.5.2.
---
> chore: bump client to 0.5.2

- CHANGELOG.md
- docs/index.md
- docs/walkthrough/basic-concepts.md
- docs/walkthrough/choose-backbone.md
- docs/walkthrough/create-training-data.md
- docs/walkthrough/integrate-with-jina.md
- docs/walkthrough/run-job.md
- docs/walkthrough/save-model.md
Improve documentation according to feedback
---
Implements the documentation according to the points listed in #523
> docs: implement feedback

- CHANGELOG.md
- finetuner/run.py
- tests/conftest.py
> fix: log streaming and staging env

- CHANGELOG.md
- setup.cfg
- setup.py
> chore: prepare release 0.6.0

- CHANGELOG.md
- README.md
- docs/get-started/design-principles.md
- docs/get-started/installation.md
- docs/tasks/image-to-image.md
- docs/tasks/text-to-image.md
- docs/tasks/text-to-text.md
- finetuner/run.py
Added some small fixes in documentation
---
> docs: varies minor small improvements

- CHANGELOG.md
- setup.py
chore bump hubble client version
---
> chore bump hubble client version

- CHANGELOG.md
- finetuner/client/base.py
- finetuner/client/client.py
- finetuner/client/session.py
- finetuner/constants.py
- tests/conftest.py
Preserve headers in redirects to the same domain.
> fix: redirect headers

- CHANGELOG.md
- setup.cfg
> chore: release `0.6.1`

- .github/workflows/pr.yml
- CHANGELOG.md
- docs/_templates/page.html
- docs/tasks/text-to-text.md
- setup.py
due up upstream change finetuner docs need to update
---
> docs: fix template

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/client/client.py
- finetuner/console.py
- finetuner/model.py
- finetuner/run.py
> Fix log messages

- .pre-commit-config.yaml
- CHANGELOG.md
- setup.py
bump flake8 version, old version failed to lint code because of [this](https://github.com/python/importlib_metadata/issues/406) 
---
> ci: bump flake8

- CHANGELOG.md
- docs/walkthrough/integrate-with-jina.md
- setup.cfg
- setup.py
> chore: release 0.6.3

- CHANGELOG.md
- Makefile
- finetuner/__init__.py
- finetuner/model.py
- setup.py
> feat: convert package to namespace package

- CHANGELOG.md
- docs/notebooks/image_to_image.ipynb
- docs/notebooks/image_to_image.md
- docs/notebooks/text_to_image.ipynb
- docs/notebooks/text_to_image.md
- docs/notebooks/text_to_text.ipynb
- docs/notebooks/text_to_text.md
Update Notebooks with latest changes implemented by the next release
---
- remove setting a version in `pip install`
- change `notebook_login` to `login`
> refactor: update notebooks

- setup.py
chore: bump commons and stubs version
---
> chore: bump commons and stubs version

- CHANGELOG.md
- setup.cfg
> chore: release 0.6.6

- CHANGELOG.md
- docs/notebooks/text_to_image.md
- finetuner/experiment.py
- setup.py
- tests/integration/test_runs.py
- tests/unit/test_experiment.py
- update commons and stubs versions
- bump hubble sdk and docarray
- add import for EvaluationCallback in  text-to-image example
- fix configuration of `num_items_per_class`
---
> fix: dependency and callback import

- CHANGELOG.md
- setup.cfg
> chore: release 0.6.7

- README.md
Ticket: https://github.com/jina-ai/team-tech-content/issues/37
General copyediting and language fixes to the README.md file.
---
> docs: copyedit readme

- README.md
> Revert "docs: copyedit readme"

- CHANGELOG.md
- README.md
Undo whatever went wrong with previous attempt to edit README.md, and add changelog line
https://github.com/jina-ai/team-tech-content/issues/37
---
> chore: mod changelog

- CHANGELOG.md
- setup.cfg
> chore: release `0.7.0`

- CHANGELOG.md
- setup.py
- tests/unit/test_experiment.py
> chore: bump commons and stubs

- CHANGELOG.md
> chore: update date in changelog

- docs/notebooks/mesh_to_mesh.md
> docs: fix typo to broken link

- CHANGELOG.md
- setup.cfg
- setup.py
Release Finetuner to 0.7.2.
---
> chore: release 072

- README.md
Small change in the documentation, access to our infra is not free
> docs: remove line about free infrastructure

- CHANGELOG.md
- finetuner/__init__.py
- finetuner/experiment.py
- finetuner/model.py
- setup.py
- tests/unit/test_client.py
- tests/unit/test_experiment.py
Since now we support data generation job, some adjustments in the client is needed.
---
> refactor: adjust schema based on job type

- CHANGELOG.md
- setup.cfg
Release Finetuner to 0.7.5.
---
> chore: release 075

- CHANGELOG.md
- setup.cfg
release 0.7.7, includes GPL and several bug fixes. The last release before 0.8.x era.
---
> chore: release 077

- CHANGELOG.md
- docs/notebooks/data_synthesis.ipynb
- docs/notebooks/data_synthesis.md
- docs/walkthrough/choose-backbone.md
- finetuner/__init__.py
- finetuner/experiment.py
- finetuner/finetuner.py
- finetuner/model.py
- setup.py
1. bump commons and stubs to latest core release
2. update supported backbones
3. update data synthesis notebook
---
> feat: add multilingual model

- CHANGELOG.md
- setup.cfg
> chore: release 0.7.8

- CHANGELOG.md
- docs/concepts/loss-functions.md
Add loss function page for docs refactoring.
To review: https://ft-docs-loss--jina-docs.netlify.app/docs-loss/concepts/loss-functions/
---
> docs: loss

- CHANGELOG.md
- docs/get-started/pretrained.md
- setup.cfg
> chore: release 080

- CHANGELOG.md
- docs/get-started/pretrained.md
fix huggingface model link
---
> docs: fix hf link

- CHANGELOG.md
- docs/get-started/pretrained.md
- tests/integration/test_hf_models.py
Remove duplicate sentence in documentation page.
---
> docs: improve embedding page
